import '../model/course_model.dart';

class AppLists {
  static const List<String> courseOptionList = [
    "All",
    "AI & ML",
    "Product",
    "Sales",
    "Public Speaking",
    "Design Thinking",
    "Business Strategy",
  ];

  static List<Course> courseList = [
    Course(
      name: "Artificial\nIntelligence Basics",
      lessons: 15,
      category: "AI & ML",
      price: 1500,
      imageUrl: "assets/images/ai_1.png",
    ),
    Course(
      name: "Machine Learning\nwith Python",
      lessons: 18,
      category: "AI & ML",
      price: 1800,
      imageUrl: "assets/images/ai_2.png",
    ),
    Course(
      name: "Deep Learning\nFoundations",
      lessons: 20,
      category: "AI & ML",
      price: 2200,
      imageUrl: "assets/images/ai_3.png",
    ),
    Course(
      name: "AI\nfor Everyone",
      lessons: 10,
      category: "AI & ML",
      price: 1200,
      imageUrl: "assets/images/ai_4.png",
    ),
    Course(
      name: "Data Science\nEssentials",
      lessons: 16,
      category: "AI & ML",
      price: 1600,
      imageUrl: "assets/images/ai_5.png",
    ),
    Course(
      name: "ML for\nMobile Apps",
      lessons: 14,
      category: "AI & ML",
      price: 1400,
      imageUrl: "assets/images/ai_6.png",
    ),
    Course(
      name: "Computer Vision\nin Practice",
      lessons: 17,
      category: "AI & ML",
      price: 1700,
      imageUrl: "assets/images/ai_7.png",
    ),
    Course(
      name: "Natural Language\nProcessing",
      lessons: 15,
      category: "AI & ML",
      price: 1500,
      imageUrl: "assets/images/ai_8.png",
    ),
    Course(
      name: "AI Model\nDeployment",
      lessons: 12,
      category: "AI & ML",
      price: 1300,
      imageUrl: "assets/images/ai_9.png",
    ),
    Course(
      name: "Predictive\nAnalytics",
      lessons: 13,
      category: "AI & ML",
      price: 1350,
      imageUrl: "assets/images/ai_10.png",
    ),

    Course(
      name: "Intro to\nProduct Management",
      lessons: 12,
      category: "Product",
      price: 1200,
      imageUrl: "assets/images/prod_1.png",
    ),
    Course(
      name: "Agile\nfor PMs",
      lessons: 14,
      category: "Product",
      price: 1350,
      imageUrl: "assets/images/prod_2.png",
    ),

    Course(
      name: "Product\nRoadmapping",
      lessons: 10,
      category: "Product",
      price: 1100,
      imageUrl: "assets/images/prod_3.png",
    ),
    Course(
      name: "Customer\nDiscovery",
      lessons: 15,
      category: "Product",
      price: 1250,
      imageUrl: "assets/images/prod_4.png",
    ),
    Course(
      name: "Building\nMVPs",
      lessons: 11,
      category: "Product",
      price: 1300,
      imageUrl: "assets/images/prod_5.png",
    ),
    Course(
      name: "Go-To-Market\nStrategy",
      lessons: 13,
      category: "Product",
      price: 1400,
      imageUrl: "assets/images/prod_6.png",
    ),
    Course(
      name: "UX for\nPMs",
      lessons: 12,
      category: "Product",
      price: 1250,
      imageUrl: "assets/images/prod_7.png",
    ),
    Course(
      name: "Analytics for\nProducts",
      lessons: 14,
      category: "Product",
      price: 1450,
      imageUrl: "assets/images/prod_8.png",
    ),
    Course(
      name: "Leadership for\nPMs",
      lessons: 10,
      category: "Product",
      price: 1150,
      imageUrl: "assets/images/prod_9.png",
    ),
    Course(
      name: "Scaling\nProducts",
      lessons: 13,
      category: "Product",
      price: 1500,
      imageUrl: "assets/images/prod_10.png",
    ),

    Course(
      name: "Sales\n101",
      lessons: 10,
      category: "Sales",
      price: 1000,
      imageUrl: "assets/images/sales_1.png",
    ),
    Course(
      name: "B2B Sales\nMastery",
      lessons: 14,
      category: "Sales",
      price: 1300,
      imageUrl: "assets/images/sales_2.png",
    ),

    Course(
      name: "Cold Calling\nTechniques",
      lessons: 12,
      category: "Sales",
      price: 1100,
      imageUrl: "assets/images/sales_3.png",
    ),
    Course(
      name: "CRM\nBasics",
      lessons: 11,
      category: "Sales",
      price: 1150,
      imageUrl: "assets/images/sales_4.png",
    ),
    Course(
      name: "Persuasive\nSelling",
      lessons: 13,
      category: "Sales",
      price: 1250,
      imageUrl: "assets/images/sales_5.png",
    ),
    Course(
      name: "Negotiation\nSkills",
      lessons: 15,
      category: "Sales",
      price: 1400,
      imageUrl: "assets/images/sales_6.png",
    ),
    Course(
      name: "Sales Funnel\nOptimization",
      lessons: 10,
      category: "Sales",
      price: 1200,
      imageUrl: "assets/images/sales_7.png",
    ),
    Course(
      name: "Closing Deals\nLike a Pro",
      lessons: 16,
      category: "Sales",
      price: 1350,
      imageUrl: "assets/images/sales_8.png",
    ),
    Course(
      name: "Email\nOutreach",
      lessons: 9,
      category: "Sales",
      price: 1050,
      imageUrl: "assets/images/sales_9.png",
    ),
    Course(
      name: "Lead Generation\nTactics",
      lessons: 12,
      category: "Sales",
      price: 1250,
      imageUrl: "assets/images/sales_10.png",
    ),

    Course(
      name: "Speaking with\nConfidence",
      lessons: 10,
      category: "Public Speaking",
      price: 1000,
      imageUrl: "assets/images/speak_1.png",
    ),
    Course(
      name: "Body Language\nMastery",
      lessons: 12,
      category: "Public Speaking",
      price: 1150,
      imageUrl: "assets/images/speak_2.png",
    ),
    Course(
      name: "Overcoming\nStage Fear",
      lessons: 11,
      category: "Public Speaking",
      price: 1100,
      imageUrl: "assets/images/speak_3.png",
    ),
    Course(
      name: "Storytelling\nSkills",
      lessons: 13,
      category: "Public Speaking",
      price: 1250,
      imageUrl: "assets/images/speak_4.png",
    ),
    Course(
      name: "Effective\nPresentations",
      lessons: 14,
      category: "Public Speaking",
      price: 1300,
      imageUrl: "assets/images/speak_5.png",
    ),
    Course(
      name: "Impromptu\nSpeaking",
      lessons: 10,
      category: "Public Speaking",
      price: 1050,
      imageUrl: "assets/images/speak_6.png",
    ),
    Course(
      name: "Public Speaking\nfor Interviews",
      lessons: 15,
      category: "Public Speaking",
      price: 1350,
      imageUrl: "assets/images/speak_7.png",
    ),
    Course(
      name: "TED Talk\nTechniques",
      lessons: 12,
      category: "Public Speaking",
      price: 1200,
      imageUrl: "assets/images/speak_8.png",
    ),
    Course(
      name: "Mastering\nVocal Tone",
      lessons: 11,
      category: "Public Speaking",
      price: 1150,
      imageUrl: "assets/images/speak_9.png",
    ),
    Course(
      name: "Engaging an\nAudience",
      lessons: 13,
      category: "Public Speaking",
      price: 1250,
      imageUrl: "assets/images/speak_10.png",
    ),

    Course(
      name: "Intro to\nDesign Thinking",
      lessons: 10,
      category: "Design Thinking",
      price: 1000,
      imageUrl: "assets/images/design_1.png",
    ),
    Course(
      name: "Empathy\nMapping",
      lessons: 11,
      category: "Design Thinking",
      price: 1100,
      imageUrl: "assets/images/design_2.png",
    ),
    Course(
      name: "User-Centered\nDesign",
      lessons: 13,
      category: "Design Thinking",
      price: 1250,
      imageUrl: "assets/images/design_3.png",
    ),
    Course(
      name: "Ideation\nTechniques",
      lessons: 12,
      category: "Design Thinking",
      price: 1150,
      imageUrl: "assets/images/design_4.png",
    ),
    Course(
      name: "Prototyping\nFast",
      lessons: 10,
      category: "Design Thinking",
      price: 1050,
      imageUrl: "assets/images/design_5.png",
    ),
    Course(
      name: "Feedback\nLoops",
      lessons: 11,
      category: "Design Thinking",
      price: 1100,
      imageUrl: "assets/images/design_6.png",
    ),
    Course(
      name: "UX Research\nBasics",
      lessons: 13,
      category: "Design Thinking",
      price: 1300,
      imageUrl: "assets/images/design_7.png",
    ),
    Course(
      name: "Testing Your\nIdeas",
      lessons: 14,
      category: "Design Thinking",
      price: 1350,
      imageUrl: "assets/images/design_8.png",
    ),
    Course(
      name: "Design Thinking\nfor Teams",
      lessons: 12,
      category: "Design Thinking",
      price: 1250,
      imageUrl: "assets/images/design_9.png",
    ),
    Course(
      name: "Creative Problem\nSolving",
      lessons: 15,
      category: "Design Thinking",
      price: 1400,
      imageUrl: "assets/images/design_10.png",
    ),

    Course(
      name: "Business Models\nExplained",
      lessons: 10,
      category: "Business Strategy",
      price: 1200,
      imageUrl: "assets/images/bs_1.png",
    ),
    Course(
      name: "Strategic Planning\nBasics",
      lessons: 12,
      category: "Business Strategy",
      price: 1300,
      imageUrl: "assets/images/bs_2.png",
    ),
    Course(
      name: "Market Analysis\nTechniques",
      lessons: 14,
      category: "Business Strategy",
      price: 1350,
      imageUrl: "assets/images/bs_3.png",
    ),
    Course(
      name: "Competitive\nPositioning",
      lessons: 11,
      category: "Business Strategy",
      price: 1250,
      imageUrl: "assets/images/bs_4.png",
    ),
    Course(
      name: "SWOT Analysis\nMastery",
      lessons: 10,
      category: "Business Strategy",
      price: 1200,
      imageUrl: "assets/images/bs_5.png",
    ),
    Course(
      name: "Growth\nHacking",
      lessons: 15,
      category: "Business Strategy",
      price: 1400,
      imageUrl: "assets/images/bs_6.png",
    ),
    Course(
      name: "KPI\nManagement",
      lessons: 12,
      category: "Business Strategy",
      price: 1300,
      imageUrl: "assets/images/bs_7.png",
    ),
    Course(
      name: "OKRs for\nTeams",
      lessons: 13,
      category: "Business Strategy",
      price: 1350,
      imageUrl: "assets/images/bs_8.png",
    ),
    Course(
      name: "Digital\nTransformation",
      lessons: 16,
      category: "Business Strategy",
      price: 1500,
      imageUrl: "assets/images/bs_9.png",
    ),
    Course(
      name: "Business Strategy\nExecution",
      lessons: 14,
      category: "Business Strategy",
      price: 1450,
      imageUrl: "assets/images/bs_10.png",
    ),
  ];
}
